settings_a:
  config:
    XY_GRID_RESOLUTION: 0.1     # [m]
    YAW_GRID_RESOLUTION: 0.26   # [rad]
    GOAL_TYAW_TH: 0.08          # [rad]
    MOTION_RESOLUTION: 0.01      # [m]
    N_STEER: 20.0               # number of steer command
    EXTEND_AREA: 0.5            # [m] map extend length
    SKIP_COLLISION_CHECK: 4     # skip number for collision check
  cost:
    SB_COST: 100.0             # switch back penalty cost
    BACK_COST: 50.0             # backward penalty cost
    STEER_CHANGE_COST: 5.0     # steer angle change penalty cost
    STEER_COST: 5.0            # steer angle penalty cost
    JACKKNIF_COST: 500.0       # Jackknife cost
    H_COST: 5.0                # Heuristic cost

settings_b:
  config:
    XY_GRID_RESOLUTION: 1.0     # [m]
    YAW_GRID_RESOLUTION: 0.26   # [rad]
    GOAL_TYAW_TH: 0.08          # [rad]
    MOTION_RESOLUTION: 0.1      # [m]
    N_STEER: 20.0               # number of steer command
    EXTEND_AREA: 5.0            # [m] map extend length
    SKIP_COLLISION_CHECK: 4     # skip number for collision check
  cost:
    SB_COST: 100.0             # switch back penalty cost
    BACK_COST: 5.0             # backward penalty cost
    STEER_CHANGE_COST: 5.0     # steer angle change penalty cost
    STEER_COST: 1.0            # steer angle penalty cost
    JACKKNIF_COST: 200.0       # Jackknife cost
    H_COST: 5.0                # Heuristic cost


