trailer_a:
  d0: 0.353   # [m] tractor's wheelbase
  d1: 0.856   # [m] wheelbase from tractor's rear axle to trailer's rear axle
  dl: 0.500   # [m] trailer's length
  w: 0.26     # [m] wheeltrack
  tr: 0.05    # [m] tire radius
  tw: 0.05    # [m] tire width
  margin: 0.2 # 1, ratio of distance from tire to vehicle boundary, the base is d0, d1 and w

trailer_b: 
  d0: 3.53   # [m] tractor's wheelbase
  d1: 8.56   # [m] wheelbase from tractor's rear axle to trailer's rear axle
  dl: 5.00   # [m] trailer's length
  w: 2.6     # [m] wheeltrack
  tr: 0.5    # [m] tire radius
  tw: 0.5    # [m] tire width
  margin: 0.2 # 1, ratio of distance from tire to vehicle boundary, the base is d0, d1 and w

